# Generated by Django 4.2.14 on 2024-07-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='стоимость обучения'),
        ),
    ]
