# Generated by Django 4.2.14 on 2024-07-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='стоимость обучения'),
        ),
    ]
